codecov:
  require_ci_to_pass: false #This setting will update the bot regardless of whether or not tests pass

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
  precision: 2
  round: down
  range: "66...100"

flags:
  unit:
    carryforward: false
  e2e-ci:
    carryforward: false
  e2e-full:
    carryforward: true

comment:
  layout: "diff,flags,files,footer"
  behavior: default
  require_changes: false
  show_carryforward_flags: true
